name: Auto-merge Dependabot
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, edited, ready_for_review]
permissions:
  pull-requests: write
  contents: write
jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: meta
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve & auto-merge security + patch/minor
        if: steps.meta.outputs.update-type != 'version-update:semver-major'
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge  "$PR_URL" --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
